name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.11'
      - name: Lint by pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install '.[test]'
      - name: Run test
        run: pytest
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.11'
      - name: Install dependencies
        run: pip install '.[doc]'
      - name: Run check
        run: make -C docs linkcheck
